/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Mentor = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'qualifications' : IDL.Text,
});
export const VideoSubmission = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'name' : IDL.Text,
  'qualifications' : IDL.Text,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'createMentor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getMentorById' : IDL.Func([IDL.Nat], [Mentor], ['query']),
  'getVideoById' : IDL.Func([IDL.Nat], [VideoSubmission], ['query']),
  'listMentors' : IDL.Func([IDL.Text], [IDL.Vec(Mentor)], ['query']),
  'listVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoSubmission)], ['query']),
  'submitVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Mentor = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'qualifications' : IDL.Text,
  });
  const VideoSubmission = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'name' : IDL.Text,
    'qualifications' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'createMentor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'getMentorById' : IDL.Func([IDL.Nat], [Mentor], ['query']),
    'getVideoById' : IDL.Func([IDL.Nat], [VideoSubmission], ['query']),
    'listMentors' : IDL.Func([IDL.Text], [IDL.Vec(Mentor)], ['query']),
    'listVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoSubmission)], ['query']),
    'submitVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };