/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Mentor {
  'id' : bigint,
  'created' : Time,
  'contactInfo' : string,
  'name' : string,
  'qualifications' : string,
}
export type Time = bigint;
export interface VideoSubmission {
  'id' : bigint,
  'created' : Time,
  'name' : string,
  'qualifications' : string,
  'videoUrl' : string,
}
export interface _SERVICE {
  'createMentor' : ActorMethod<[string, string, string], bigint>,
  'getMentorById' : ActorMethod<[bigint], Mentor>,
  'getVideoById' : ActorMethod<[bigint], VideoSubmission>,
  'listMentors' : ActorMethod<[string], Array<Mentor>>,
  'listVideos' : ActorMethod<[string], Array<VideoSubmission>>,
  'submitVideo' : ActorMethod<[string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];